---
- hosts: localhost
  connection: local

  tasks:
  - name: Create variable from command
    shell: curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/userData?api-version=2021-01-01&format=text" | base64 --decode
    register: command_output
  - debug: msg="{{command_output.stdout}}"

  - set_fact:
      gslt: "{{ command_output.stdout }}"

  - name: "Add steam repository Ubuntu"
    apt_repository:
      repo: "deb http://us.archive.ubuntu.com/ubuntu/ bionic multiverse"
      state: present
      update_cache: yes
    become: yes

  - name: Enable i386 architecture
    command: dpkg --add-architecture i386
    become: yes

  - name: Upgrade all apt packages
    apt:
      force_apt_get: yes
      upgrade: dist
    become: yes

  - name: Ensure apt cache is up to date
    apt: update_cache=yes
    become: yes

  - name: Say yes to licence agreement
    shell: echo steam steam/question select "I AGREE" | sudo debconf-set-selections
    become: yes

  - name: "Installing packages"
    apt:
      name: ['lib32gcc1', 'lib32stdc++6', 'software-properties-common', 'steamcmd']
      state: present
    become: yes

  - name: Update steamcmd
    shell: |
      cd ~
      steamcmd +quit

  - name: Create directory for csgo
    become: yes
    become_user: 'steam'
    file:
      path: ~/csgo
      state: directory
      mode: '0755'

  - name: Install CS
    shell: |
      steamcmd +force_install_dir ~/csgo +login anonymous +app_update 740 validate +quit